services:
  postgres:
    image: postgres:16
    container_name: ecommerce_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_password
      POSTGRES_DB: ecommerce_order_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
